@baseUrl = http://localhost:3000
@token = {{authenticate.response.body.access_token}}

# @name create_user
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Fernando",
  "userName": "guerreiro",
  "email": "f.luhis@gmail.com",
  "birthDate": "1997-02-15T00:00:00",
  "password": "051177"
}

###

# @name get_user_by_id
GET  {{baseUrl}}/user/bba18dfc-9077-48c5-942c-e3bdd1df22eb
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name authenticate
POST {{baseUrl}}/session
Content-Type: application/json

{
  "email": "f.luhis@gmail.com",
  "password": "051177"
}

###

# @name create_category
POST {{baseUrl}}/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "ação"
}

###

# @name list_categories
GET  {{baseUrl}}/category
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_category_by_id
GET  {{baseUrl}}/category/70e72f19-0717-493c-a5a4-c407f1c0063b
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name create_book
POST {{baseUrl}}/book
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "As Aventuras de João e Maria 3",
  "description": "Um conto encantador sobre duas crianças que encontram uma casa feita de doces na floresta.",
  "audience": "TEENS",
  "language": "PORTUGUESE",
  "authorRights": "Todos os direitos reservados",
  "coverImage": "http://example.com/images/joao_e_maria.jpg",
  "userId": "bba18dfc-9077-48c5-942c-e3bdd1df22eb",
  "categoryId": "3406942c-95e9-4b71-b1b7-e6af21b2c84b",
  "tags": ["Conto de Fadas", "Aventura", "Fantasia"]
}

###

# @name get_book_rating
POST {{baseUrl}}/book
Content-Type: application/json
Authorization: Bearer {{token}}

# @name create_chapter
POST {{baseUrl}}/chapter
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "chapterName": "capitulo 1",
  "chapterContent": "<p><b>Teste</b></p>",
  "chapterImage": "string",
  "bookId": "5fe148e4-44a8-4d6d-8b9e-4a44efa066f3"
}

###

# @name create_review
POST {{baseUrl}}/review
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "bba18dfc-9077-48c5-942c-e3bdd1df22eb",
  "bookId": "5fe148e4-44a8-4d6d-8b9e-4a44efa066f3",
  "rating": 1,
  "comment": "Este livro foi muito interessante e envolvente!"
}

### 

# @name get_review
GET {{baseUrl}}/review/rating/5fe148e4-44a8-4d6d-8b9e-4a44efa066f3
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name create_comment
POST {{baseUrl}}/comment
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "Conteudo do comentário",
  "userId": "bba18dfc-9077-48c5-942c-e3bdd1df22eb",
  "targetType": "chapter",
  "targetId": "5fe148e4-44a8-4d6d-8b9e-4a44efa066f3"
}

###
# @name get_comments
GET {{baseUrl}}/comment
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name create_paragraph
GET {{baseUrl}}/paragraph
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "",
  "chapterId": "",
}

###
# @name get_paragraph_comments
GET {{baseUrl}}/paragraph/5fe148e4-44a8-4d6d-8b9e-4a44efa066f3/comments
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name create_tag
POST {{baseUrl}}/tag
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test"
}

###
# @name create_character_in_lot
POST {{baseUrl}}/create-in-lot
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test"
}

"bookId": "5fe148e4-44a8-4d6d-8b9e-4a44efa066f3"